apiVersion: v1
kind: Service
metadata:
  name: app-web
spec:
  type: NodePort
  selector:
    app: app-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web
  labels:
    app: app-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-web
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
        - name: app-web
          image: khalil15832/app-web:latest
          ports:
            - containerPort: 80
